AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'bin/**/*'

Style/BlockComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - '**/*.rake'

Style/MultilineIfModifier:
  AutoCorrect: false

Style/NumericLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false