AllCops:
  Exclude:
    - 'app/controllers/admin/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'config/**/*.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Metrics/MethodLength:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'spec/rails_helper.rb'

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  Exclude:
    - '**/*.rake'

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineIfModifier:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma